### ISSUE TITLE
Can I selfhost the server?

### ISSUE THREAD

**Issue by ippocratis** [zood/oscar#25]
The android app also does not have any options to select a custom server during segistering

**Comment by arashpayan** [comment]
You can certainly run your own server and set up all the dependencies necessary to make it operational, but as you noted, you'd have to modify and build a custom client in order to be able to use it. Even if you do that, the server is not designed to federate with other instances, so you would only be able to share or see location with other people who are also using your client and server.

I can't think of any benefits to doing that. The protocol has been designed so I (the server operator) don't know where anyone is. The server is primarily a key-value store used by the clients for storing encrypted payloads, and it can't see see inside any of the payloads.

Of course, you're more than welcome to actually set up an instance of the server. That's why the code is open. :-)
